### ISSUE TITLE
Null points

### ISSUE THREAD

**Issue by TorsteinHonsi** [paulo-raca/highcharts-contour#1]
Great plugin, thanks for contributing!

It might not be relevant for your use cases, but I add this issue for the records: Your [temperature demo](http://jsfiddle.net/nsj5uzdw/) contains a null point, which seems to float out towards the neighbour points. I would expect null points to simple be ignored, not drawn and not leave a trace in neighbours.

**Comment by paulo-raca** [comment]
I'm sorry I didn't notice this issue earlier...

Thanks for testing my plugin and reporting the error.
It seems easy enough, I'll have a fix soon.
