### ISSUE TITLE
3D surface tooltip colors broken

### ISSUE THREAD

**Issue by historicbruno** [paulo-raca/highcharts-contour#10]
A change in 8aa6c5559ef1e36f4b70a589f881104946bbdd5a (from #8) broke tooltip colors. Compare these two JSFiddles:
http://jsfiddle.net/yw56rtus/15/ <-- tooltip colors working in 607ae97c3e9787b7b3c84abcd5f7e513f25f8587
http://jsfiddle.net/yw56rtus/16/ <-- tooltip colors broken in 8aa6c5559ef1e36f4b70a589f881104946bbdd5a 

Notice how the tooltip outline color appears random in the second example; it should match the gray shades of the surface points, as in the first example.

**Note**: tooltips are completely broken when using the upstream Highcharts release (#6), and also there is a bug in Highcharts which prevents the point marker from being the correct color. I fixed the second problem locally, by modifying the Highcharts source as follows (not yet submitted upstream):
```diff
--- a/highcharts.src.js
+++ b/highcharts.src.js
@@ -18139,12 +18139,14 @@ extend(Point.prototype, {
 						stateMarkerGraphic.currentSymbol = newSymbol;
 					}
 
-				// Move the existing graphic
+				// Update the existing graphic
 				} else {
-					stateMarkerGraphic[move ? 'animate' : 'attr']({ // #1054
-						x: plotX - radius,
-						y: plotY - radius
-					});
+				    stateMarkerGraphic[move ? 'animate' : 'attr'](merge(
+                        pointAttr, { // #1054
+						    x: plotX - radius,
+						    y: plotY - radius
+                        }
+                    ));
 				}
 			}
```

**Comment by paulo-raca** [comment]
I had never noticed that the tooltip edge had a matching color!
But it's fixed now.

Unfortunately, fixing the point marker color upstream won't help you, since the tooltip currently works only on my very old branch :(

But I'll get to #6 eventually, I promise!
