### ISSUE TITLE
Countour curve examples are broken

### ISSUE THREAD

**Issue by marianopeck** [paulo-raca/highcharts-contour#11]
Hi @paulo-raca 

I am trying to see the Countour examples but they all look broken... any idea?

**Comment by paulo-raca** [comment]
Looks like I've forgotten to update the samples for a while now. I'll get this fixed

**Comment by paulo-raca** [comment]
I've updated the examples. Is it working for you now?

**Comment by marianopeck** [comment]
Yes cool, they work now!
