### ISSUE TITLE
Error: <linearGradient> attribute x2: Expected length

### ISSUE THREAD

**Issue by hoanphi2201** [paulo-raca/highcharts-contour#14]
Hello, I'm drawing a contour with highcharts. when i give array with > 400 element(it works nomally with a array 200 element), when resize or update chart, I received the following error. Can you point out what is the problem here? 
Thank you .
<img width="833" alt="Screen Shot 2019-05-14 at 09 42 17" src="https://user-images.githubusercontent.com/36753744/57667121-9ca1d180-762c-11e9-8728-e935ecdec8c0.png">

When i call setSize :
chart.setSize(null, ($(window).height() / parseInt(config["rowcount"])) - (chart.marginBottom + chart.plotTop));
or chart.update(options);

**Comment by paulo-raca** [comment]
Can you provide me a reproduction? (E.g., jsfiddle)?

**Comment by hoanphi2201** [comment]
https://jsfiddle.net/phihoan2201/2nb8op56/1/
 You can see it.

**Comment by hoanphi2201** [comment]
It seems that resizing makes colors reload.

**Comment by hoanphi2201** [comment]
I fixed it by remove the series contour before update then I add it again. That is a solution that is not really optimal. And I still do not really understand the cause of the error

**Comment by paulo-raca** [comment]
I'll leave it open and look for a Better solution

**Comment by hoanphi2201** [comment]
Yes, thank you @paulo-raca

**Comment by paulo-raca** [comment]
This has been fixed on latest version: https://jsfiddle.net/de5sapy3/

**Comment by hoanphi2201** [comment]
Great @paulo-raca
