### ISSUE TITLE
Needing labels on the contour lines

### ISSUE THREAD

**Issue by allycat283196** [paulo-raca/highcharts-contour#16]
For my project I have 5 lines that have different values. How I add labels to the lines so that I can tell which line is which data value? I have looked at the highcharts-contour.js and I don't see anything that can create this, is there something i'm missing?

**Comment by paulo-raca** [comment]
I assume you want something like [this](https://gis.stackexchange.com/a/170476) ?

Sounds like a nice thing to have, but right now it has not been implemented -- and unfortunately it sounds quite difficult to.

I usually rely on the surface color, but it should be straightforward to support different line colors (And maybe styles?) for each line value

**Comment by DanialV** [comment]
I need this feature too.

**Comment by paulo-raca** [comment]
Sorry, this is not feasible to implement.

However adding labels where the contours touch the edges is already supported: https://jsfiddle.net/0Ljcotw8/
