### ISSUE TITLE
Demos didn't work correctly

### ISSUE THREAD

**Issue by Denyllon** [paulo-raca/highcharts-contour#17]
We noticed that the demos are not working as worked before, and some kind of iframe refreshes occur in all of JSFiddle examples. It usually happens while an attend to interact available inputs (e.g choosing the axes).

Also found out that it backs to normal when removed all interactive parts of the demo, and passed a _pure_ array with contour options like below:
```js
  chart.series[0].update({
    "contours": ['value']
  }, false);
```
Looks like the problem is caused by the fact, that the `axes` variable is an array, but with two unnecessary keys like `context` and `prevObject`, which are coming from jQuery. After converting this variable to array everything start to work correctly.

Live example: https://jsfiddle.net/BlackLabel/hw6Lpx3u/

**Comment by paulo-raca** [comment]
Hello!


Thanks you!

To be honest I haven't used/updated the plug-in in a while, and I didn't
even realize it was broken 😅

I'll update the examples later

Em sex, 24 de abr de 2020 10:12, Daniel Studencki <notifications@github.com>
escreveu:

**Comment by Denyllon** [comment]
Sound good! Thank you :)

**Comment by Denyllon** [comment]
Please let me know right after pushing a fix, because I'm waiting with presenting this plugin to a potential Highcharts client ;)

**Comment by paulo-raca** [comment]
I've updated the examples with the `.toArray()`, as you suggested.

However the examples the rely on `dataFunc` continue broken on Highcharts 7+, I'll take a look at it next

**Comment by paulo-raca** [comment]
All demos are working again.
Thank you for bringing it to my attention again
