### ISSUE TITLE
How to add plugin in vue

### ISSUE THREAD

**Issue by dharmatv** [paulo-raca/highcharts-contour#19]
We have tried following ways in vue to display contour chart.

1. Included CDN in index.html, shows following screenshot 
https://snipboard.io/5pLyeV.jpg
2. Tried a require function also
3. append link dynamically to head tag

But getting errors like show the following screenshot
https://snipboard.io/Ah65So.jpg

Could u please anyone provide any other way to do for this issue

**Comment by paulo-raca** [comment]
Sorry, I don't know anything about how Vue works, but AFAICT that should be it.

Can you send me a fiddle that reproduces the issue?

**Comment by dharmatv** [comment]
Thanks for reply @paulo-raca, I haven't mentioned in the above comment is -  is it possible to provide npm module.
why because in my project CDN link wasn't fitted, could u please

**Comment by paulo-raca** [comment]
This is finally available as an npm module :rocket: 

Sorry it took too long :sweat_smile:
