### ISSUE TITLE
Contour lines

### ISSUE THREAD

**Issue by reyhaan** [paulo-raca/highcharts-contour#2]
Hi, great plugin for smooth contour graph. It would be great if you add contour lines as well, as shown in this image: http://www.giatecscientific.com/wp-content/uploads/2014/01/half-cell-corrosion-potential-NDT-21.jpg 
We kinda need it for our app right now and I am not able to figure out how to add them.

**Comment by paulo-raca** [comment]
Hello,
Sorry for the very, very, very late reply, I only noticed it now.

Contour lines were in my initial plan and I have a pretty good idea about how I would implement it.
Unfortunately, I've got other things going on right now and have no plans to work on it.

If you are still interested and willing to write the code, I can help with some comments and code reviews. Otherwise, I'll leave the issue for now.

**Comment by angelcasm** [comment]
hey i interested to participe with that idea for the countur lines like a surface lines in others libraries if you get me a chance and you guideme for the point of your code for render the contour and write a sub for draw the lines. sorry for my english

**Comment by paulo-raca** [comment]
Welcome aboard!

Each contour line is drawn where the chart assumes one of a few specific value (e.g., Temperature=0,10,20,30). These values are the "Ticks" of the valueAxis (also known as Color Axis and as Y Axis (in 3D)).

My rough idea is to process contour lines per-triangle (inside `drawTriangle()`).
Within each triangle, the data is assumed to be a linear. You can use Math™ to find the line segment on the plane where value=tickValue. Makes sense?

**Comment by paulo-raca** [comment]
There already is some code for drawing lines inside `drawTriangle()`.
There is this (undocumented?) featured where it draws the edges when running in 3D mode. e.g.: http://jsfiddle.net/7j0ywvkb/

Just plug your extra SVG edges here: https://github.com/paulo-raca/highcharts-contour/blob/master/highcharts-contour.js#L223-237

**Comment by angelcasm** [comment]
i only ordered your code , the function exist


is not precice but look fine





//add in your js

drawGraph: function () {
.
.
.
// Render each triangle
for (i = 0; i < triangle_count; i++) {

   series.drawTriangle(series.triangles[i], points, egde_count);

   if (series.options.showSurfaceLines == true) {
       series.addSurfaceLines(series.triangles[i], points, series.options,
renderer);
   }
}

add two options in the series
series: [{
                    name: named,
                    //colorByPoint: true,
                    lineWidth: 1,
                    data: data,
                    //showEdges: true,
                    showSurfaceLines: true,
                    surfaceLinesTypes: ['grid''],
                    //surfaceLinesTypes: ['grid','triangle'],
                    turboThreshold: 1000000000

                }]

and voila for me thanks
[image: Imágenes integradas 1]



2016-05-17 15:57 GMT-05:00 Paulo Costa <notifications@github.com>:

**Comment by paulo-raca** [comment]
Wait, what?
It cannot be _that_ easy. Can it?
Where is `series.addSurfaceLines()` defined?

Anyway, could you create a merge request?

**Comment by paulo-raca** [comment]
Now that you brought it up, I actually felt like implementing it.
A few examples:
- 2D: http://jsfiddle.net/acyfjeg8/
- 3D: http://jsfiddle.net/bgxd3tgr/

@angelcasm, sorry I didn't wait for your pull request. I just felt excited about this feature and decided to implement it. Let me know if you have any suggestions.

**Comment by angelcasm** [comment]
Thanks for the feature .

**Comment by angelcasm** [comment]
i try draw the lines for the xaxis and yaxis over the surface but not is posible with your add and i not have idea for implementing.

**Comment by paulo-raca** [comment]
Sorry, I didn't understand what you meant

**Comment by angelcasm** [comment]
![rotated](https://cloud.githubusercontent.com/assets/19414896/15365767/10a83f76-1ce7-11e6-8b19-fae46bfd68cb.png)

like the chartfx showsurfacelines option , that draw the x axis lines and y axis lines in the surface 

trying implement but the orientation of the triangles sometimes not the correct and I trying draw independent with a path.push a line in orientation of x axis and y axis with restriction of end of surface but i very tired, regards.

**Comment by angelcasm** [comment]
i only can draw this
![rotated2](https://cloud.githubusercontent.com/assets/19414896/15365986/f7432d56-1ce7-11e6-8ce7-03bef3228941.png)
but the width of lines is relative with the number of triagles visibles for there area.

**Comment by paulo-raca** [comment]
Oh, I see.
This shouldn't be hard to implement, just change these lines to the axis/attribute you want:
https://github.com/paulo-raca/highcharts-contour/blob/master/highcharts-contour.js#L246-247

(You'll probably want to loop it over X,Y and Z axes)

I'll make it configurable later today

**Comment by angelcasm** [comment]
ok i will try, regards and thanks for your attention

**Comment by paulo-raca** [comment]
There you go, contour lines on any axis: http://jsfiddle.net/7q98Lfrq/

The key is the option `contours: ["x", "y", "z", "value"]`

**Comment by paulo-raca** [comment]
Random bonus: http://jsfiddle.net/bjvg8sgs/

**Comment by angelcasm** [comment]
Paulo is very good development , it is exactly what I needed , a greeting and good luck again your api is very very good , greetings .
