### ISSUE TITLE
Need to add contour in Angular 8 application

### ISSUE THREAD

**Issue by DivyaJegadheesan** [paulo-raca/highcharts-contour#20]
I want to add this contour plugin to our angular 8 application. But since it's not in npm and has only js file i'm facing issues in using this to include in angular.  Need help or guidelines to use this in Angular application

**Comment by paulo-raca** [comment]
Hello,
Unfortunately I have zero experience with NPM or angular, and I'm quite busy right now.

Any chance you could make the changes and send a PR?

**Comment by DivyaJegadheesan** [comment]
Hi,

I'm also busy right now  with project work. Maybe i'll try to spend some
time  and if i'm able to  do it, I'll let you know and send the PR

**Comment by paulo-raca** [comment]
This is finally available as an npm module :rocket: 

Sorry it took too long :sweat_smile:
