### ISSUE TITLE
Tooltips not working with latest Highcharts release

### ISSUE THREAD

**Issue by historicbruno** [paulo-raca/highcharts-contour#6]
First, thanks for the continued work on this plugin!

For some reason, tooltips no longer work with the latest Highcharts release. This can be verified with the demos:
http://jsfiddle.net/yw56rtus/  <-- tooltip works, using your custom fork
http://jsfiddle.net/1uohjL8b/1/ <-- no tooltips with latest Highcharts release

I suppose something changed in Highcharts, because I can't see anything in the plugin that deals with tooltips?

**Comment by historicbruno** [comment]
After checking again (Highcharts 5.0.7), I see this works now! There are a few issues with the 3D contour demo, it seems the rotation handler needs to be fixed, and series markers should be disabled for aesthetics.

**Comment by paulo-raca** [comment]
Thanks for bringing it up -- I had completely forgotten about this issue.

Actually there are now 2 bugs:
- The surface still doesn't bring up tooltip
- ,there are now undesired points above the surface (Which do bring up the tooltip)

**Comment by historicbruno** [comment]
You're right, it's only the markers which were showing the tooltip; disabling those brings back the behavior reported in this issue :/

**Comment by historicbruno** [comment]
After more testing, I think something else is going on here. Looking at the "working" demo, there are still discrete points where the tooltip works, I believe those are the data points added to the chart, and where the ugly markers are visible in the latest Highcharts. They are simply hidden by default in your branch. I can see the tooltips (testing in Chrome), but I don't want to see the markers -- unfortunately, disabling them seems to break the tooltips as well.

Obviously that's not ideal behavior, it would be nice if the tooltip could move along the entire surface, maybe that's a deeper issue in Highcharts: https://github.com/highcharts/highcharts/issues/4552

**Comment by paulo-raca** [comment]
I finallt fixed it, let me know if you have any other issues.

While it would be possible to interpolate any point on the surface, I haven't done it ye -- Maybe in the future?

**Comment by historicbruno** [comment]
Thanks!  Was the console.log statement left by accident?

**Comment by paulo-raca** [comment]
Oops...
I've just removed it
