### ISSUE TITLE
3D legend is buggy

### ISSUE THREAD

**Issue by historicbruno** [paulo-raca/highcharts-contour#7]
I notice all the 3D demos have the legend disabled, probably because of this bug. Actually the color gradient portion of the legend looks OK (if the [reversed](http://api.highcharts.com/highmaps#colorAxis.reversed) option is set). The labels even look good, but there are strange lines and another set of labels which rotate with the chart, making the legend unusable.

I am currently using a workaround of disabling the legend labels and drawing my own, but obviously it would be nicer if this was handled by Highcharts. Maybe there is some combination of options, unknown to me, which can fix this?

**Comment by paulo-raca** [comment]
This is actually problem with the Highcharts core
(Apparently they never thought someone would use ColorAxis in a 3D chart)

I've sent them a patch (https://github.com/highcharts/highcharts/pull/5498), but added a hack on highcharts-contour to make it work in the meantime

**Comment by historicbruno** [comment]
Thanks for looking into this!
